version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node:
    docker:
      - image: 'cimg/node;current-browsers'
    resouce_class: medium

commands:
  nodesetup:
    description: checkout, restore cache, save cache, install dependencies
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          app-dir: ~/project/

jobs:
  build_and_test:
    executor: 'node'
    steps:
      - nodesetup
      - run:
          name: Test
          command: |
            npm run coverage
      - restore_cache:
          keys:
          - v1-result-cache
      - run:
          name: Coverage Test
          command: |
            mv /tmp/result /tmp/result-moved || true
            npx lcov-total coverage/lcov.info > /tmp/result
            chmod u+x coveragetest.sh
            ./coveragetest.sh
      - save_cache:
          paths: converage
          key: v1-result-cache
      - store_artifacts: # Save coverage reports as artifacts 
          path: converage
          prefix: converage

workflows:
  node_build_pipeline:
    jobs:
      - build_and_test     



